######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 6 16:07:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
